##  Autor: Neco Villegas Saiz
##  Universidad de Cantabria    
##  Fecha: 03/08/2022

#Compose para 2 nodos Fog y 0 nodos Cloud

#CONFIG = fichero json
#NUM = id del nodo

#######################################################################################################

version: "3"
services:
  ########################## Nodo Master ##########################
  master_node:
    image: master_nodes
    privileged: true
    environment:
      - CONFIG=cnf/config.json
    volumes:
      - ./:/home/

  ########################## Nodos Fog ##########################
  fog_node_1:
    image: fog_nodes
    privileged: true
    environment:
      - CONFIG=cnf/config.json
      - NUM=1
    volumes:
      - ./:/home/

  fog_node_2:
    image: fog_nodes
    privileged: true
    environment:
      - CONFIG=cnf/config.json
      - NUM=2
    volumes:
      - ./:/home/

